Update main.py
"import numpy.distutils.system_info as sysinfo" causes "ImportError: cannot import name 'ccompiler' from partially initialized module 'numpy.distutils' (most likely due to a circular import)" in executable made with PyInstaller. With proposed workaround there is no error.